import { type Equipment, type MuscleGroup } from "@atlas/contracts";

/**
 * The curated exercise catalogue (blueprint/07 "biblioteca completa", ADR-0004).
 * System-owned reference data loaded by the seed. Growing it ships as new data
 * here + a re-seed; entries are keyed by their stable `slug` so the seed is
 * idempotent (existing slugs are left untouched).
 */
export interface SeedExercise {
  readonly slug: string;
  readonly name: string;
  readonly primaryMuscle: MuscleGroup;
  readonly muscles: MuscleGroup[];
  readonly equipment: Equipment;
  readonly instructions: string;
  readonly tips: string[];
  readonly variations: string[];
}

export const EXERCISE_CATALOGUE: SeedExercise[] = [
  {
    slug: "barbell-bench-press",
    name: "Supino reto com barra",
    primaryMuscle: "chest",
    muscles: ["chest", "triceps", "shoulders"],
    equipment: "barbell",
    instructions:
      "Deite no banco, segure a barra um pouco mais aberto que os ombros e desça até o peito controlando o movimento, depois empurre de volta.",
    tips: ["Mantenha as escápulas retraídas", "Não deixe os cotovelos abrirem 90°"],
    variations: ["Supino inclinado", "Supino declinado"],
  },
  {
    slug: "incline-dumbbell-press",
    name: "Supino inclinado com halteres",
    primaryMuscle: "chest",
    muscles: ["chest", "shoulders", "triceps"],
    equipment: "dumbbell",
    instructions:
      "No banco inclinado a 30–45°, empurre os halteres para cima até quase a extensão total e desça controlando.",
    tips: ["Controle a descida", "Não bata os halteres no topo"],
    variations: ["Supino reto com halteres"],
  },
  {
    slug: "push-up",
    name: "Flexão de braço",
    primaryMuscle: "chest",
    muscles: ["chest", "triceps", "core"],
    equipment: "bodyweight",
    instructions:
      "Com o corpo em prancha, desça o peito até perto do chão e empurre de volta mantendo o tronco rígido.",
    tips: ["Mantenha o corpo alinhado", "Cotovelos próximos ao corpo"],
    variations: ["Flexão inclinada", "Flexão diamante"],
  },
  {
    slug: "barbell-back-squat",
    name: "Agachamento livre",
    primaryMuscle: "legs",
    muscles: ["legs", "glutes", "core"],
    equipment: "barbell",
    instructions:
      "Com a barra apoiada no trapézio, agache empurrando o quadril para trás até as coxas ficarem paralelas e suba.",
    tips: ["Joelhos alinhados aos pés", "Mantenha o tronco ereto"],
    variations: ["Agachamento frontal", "Agachamento goblet"],
  },
  {
    slug: "romanian-deadlift",
    name: "Levantamento terra romeno",
    primaryMuscle: "legs",
    muscles: ["legs", "glutes", "back"],
    equipment: "barbell",
    instructions:
      "Com leve flexão de joelhos, desça a barra junto às pernas empurrando o quadril para trás e volte contraindo os glúteos.",
    tips: ["Coluna neutra", "Sinta o alongamento posterior"],
    variations: ["Terra romeno com halteres"],
  },
  {
    slug: "walking-lunge",
    name: "Afundo caminhando",
    primaryMuscle: "legs",
    muscles: ["legs", "glutes", "core"],
    equipment: "dumbbell",
    instructions:
      "Dê um passo à frente e desça até o joelho de trás quase tocar o chão; alterne as pernas avançando.",
    tips: ["Tronco estável", "Joelho da frente sobre o tornozelo"],
    variations: ["Afundo estático", "Afundo reverso"],
  },
  {
    slug: "deadlift",
    name: "Levantamento terra",
    primaryMuscle: "back",
    muscles: ["back", "legs", "glutes", "core"],
    equipment: "barbell",
    instructions:
      "Com a barra no chão, segure-a, mantenha a coluna neutra e suba estendendo quadril e joelhos juntos.",
    tips: ["Barra próxima ao corpo", "Não arredonde a lombar"],
    variations: ["Terra sumô"],
  },
  {
    slug: "pull-up",
    name: "Barra fixa",
    primaryMuscle: "back",
    muscles: ["back", "biceps"],
    equipment: "bodyweight",
    instructions:
      "Pendurado na barra com pegada pronada, puxe o corpo até o queixo passar a barra e desça controlando.",
    tips: ["Inicie o movimento pelas escápulas", "Evite balançar"],
    variations: ["Barra supinada", "Barra assistida"],
  },
  {
    slug: "bent-over-row",
    name: "Remada curvada",
    primaryMuscle: "back",
    muscles: ["back", "biceps", "shoulders"],
    equipment: "barbell",
    instructions:
      "Com o tronco inclinado e a coluna neutra, puxe a barra em direção ao abdômen e desça controlando.",
    tips: ["Cotovelos rentes ao corpo", "Não use impulso"],
    variations: ["Remada unilateral com halter"],
  },
  {
    slug: "overhead-press",
    name: "Desenvolvimento militar",
    primaryMuscle: "shoulders",
    muscles: ["shoulders", "triceps", "core"],
    equipment: "barbell",
    instructions:
      "Em pé, com a barra na altura dos ombros, empurre acima da cabeça até a extensão total e desça controlando.",
    tips: ["Não hiperestenda a lombar", "Aperte os glúteos para estabilizar"],
    variations: ["Desenvolvimento com halteres", "Desenvolvimento sentado"],
  },
  {
    slug: "lateral-raise",
    name: "Elevação lateral",
    primaryMuscle: "shoulders",
    muscles: ["shoulders"],
    equipment: "dumbbell",
    instructions:
      "Com halteres ao lado do corpo, eleve os braços lateralmente até a altura dos ombros e desça devagar.",
    tips: ["Cotovelos levemente flexionados", "Evite balançar o tronco"],
    variations: ["Elevação lateral no cabo"],
  },
  {
    slug: "bicep-curl",
    name: "Rosca direta",
    primaryMuscle: "biceps",
    muscles: ["biceps"],
    equipment: "dumbbell",
    instructions:
      "Com os cotovelos junto ao corpo, flexione os braços levando os halteres aos ombros e desça controlando.",
    tips: ["Não use impulso", "Controle a fase negativa"],
    variations: ["Rosca martelo", "Rosca na barra W"],
  },
  {
    slug: "triceps-pushdown",
    name: "Tríceps na polia",
    primaryMuscle: "triceps",
    muscles: ["triceps"],
    equipment: "cable",
    instructions:
      "Na polia alta, com cotovelos fixos ao lado do corpo, estenda os braços para baixo e retorne controlando.",
    tips: ["Cotovelos imóveis", "Extensão completa"],
    variations: ["Tríceps corda", "Tríceps testa"],
  },
  {
    slug: "hip-thrust",
    name: "Elevação de quadril",
    primaryMuscle: "glutes",
    muscles: ["glutes", "legs"],
    equipment: "barbell",
    instructions:
      "Com as costas apoiadas no banco e a barra sobre o quadril, eleve o quadril até a extensão e desça controlando.",
    tips: ["Contraia os glúteos no topo", "Queixo levemente para baixo"],
    variations: ["Ponte de glúteo no chão"],
  },
  {
    slug: "plank",
    name: "Prancha",
    primaryMuscle: "core",
    muscles: ["core", "shoulders"],
    equipment: "bodyweight",
    instructions:
      "Apoie antebraços e pontas dos pés, mantenha o corpo alinhado e contraído pelo tempo determinado.",
    tips: ["Não deixe o quadril cair", "Respire de forma constante"],
    variations: ["Prancha lateral", "Prancha com elevação de perna"],
  },
  {
    slug: "dumbbell-fly",
    name: "Crucifixo com halteres",
    primaryMuscle: "chest",
    muscles: ["chest", "shoulders"],
    equipment: "dumbbell",
    instructions:
      "Deitado no banco, abra os braços em arco com leve flexão de cotovelos e retorne contraindo o peito.",
    tips: ["Não desça além da linha do ombro", "Controle o movimento"],
    variations: ["Crucifixo inclinado", "Crucifixo na máquina (peck deck)"],
  },
  {
    slug: "cable-crossover",
    name: "Crossover na polia",
    primaryMuscle: "chest",
    muscles: ["chest", "shoulders"],
    equipment: "cable",
    instructions:
      "Com as polias altas, traga as mãos à frente do corpo em arco, cruzando levemente, e retorne controlando.",
    tips: ["Mantenha leve inclinação à frente", "Contraia o peito no final"],
    variations: ["Crossover polia baixa", "Crossover unilateral"],
  },
  {
    slug: "chest-press-machine",
    name: "Supino na máquina",
    primaryMuscle: "chest",
    muscles: ["chest", "triceps", "shoulders"],
    equipment: "machine",
    instructions:
      "Sente-se, empurre as alças para frente até quase estender e retorne controlando.",
    tips: ["Mantenha as costas apoiadas", "Não trave os cotovelos"],
    variations: ["Supino inclinado na máquina"],
  },
  {
    slug: "lat-pulldown",
    name: "Puxada na frente",
    primaryMuscle: "back",
    muscles: ["back", "biceps"],
    equipment: "cable",
    instructions:
      "Na polia alta, puxe a barra até a parte superior do peito, contraindo as costas, e retorne controlando.",
    tips: ["Inicie pelo movimento das escápulas", "Evite balançar o tronco"],
    variations: ["Puxada pegada fechada", "Puxada pegada supinada"],
  },
  {
    slug: "seated-cable-row",
    name: "Remada baixa na polia",
    primaryMuscle: "back",
    muscles: ["back", "biceps"],
    equipment: "cable",
    instructions:
      "Sentado, puxe a alça em direção ao abdômen mantendo as costas eretas e retorne controlando.",
    tips: ["Puxe com as costas, não com os braços", "Mantenha o tronco estável"],
    variations: ["Remada com triângulo", "Remada barra reta"],
  },
  {
    slug: "dumbbell-row",
    name: "Remada unilateral com halter",
    primaryMuscle: "back",
    muscles: ["back", "biceps"],
    equipment: "dumbbell",
    instructions:
      "Com um joelho e mão no banco, puxe o halter em direção ao quadril e desça controlando.",
    tips: ["Cotovelo rente ao corpo", "Não rotacione o tronco"],
    variations: ["Remada serrote"],
  },
  {
    slug: "leg-press",
    name: "Leg press",
    primaryMuscle: "legs",
    muscles: ["legs", "glutes"],
    equipment: "machine",
    instructions:
      "Apoie os pés na plataforma, desça flexionando os joelhos e empurre de volta sem travar.",
    tips: ["Joelhos alinhados aos pés", "Não desça além do confortável"],
    variations: ["Leg press 45°", "Leg press unilateral"],
  },
  {
    slug: "leg-extension",
    name: "Cadeira extensora",
    primaryMuscle: "legs",
    muscles: ["legs"],
    equipment: "machine",
    instructions: "Sentado, estenda os joelhos elevando o apoio e retorne controlando.",
    tips: ["Não use impulso", "Contraia o quadríceps no topo"],
    variations: ["Extensora unilateral"],
  },
  {
    slug: "leg-curl",
    name: "Cadeira flexora",
    primaryMuscle: "legs",
    muscles: ["legs"],
    equipment: "machine",
    instructions: "Deitado ou sentado, flexione os joelhos puxando o apoio e retorne controlando.",
    tips: ["Movimento controlado", "Não tire o quadril do apoio"],
    variations: ["Flexora em pé"],
  },
  {
    slug: "calf-raise",
    name: "Elevação de panturrilha",
    primaryMuscle: "legs",
    muscles: ["legs"],
    equipment: "machine",
    instructions: "Em pé, eleve os calcanhares ao máximo e desça alongando a panturrilha.",
    tips: ["Amplitude completa", "Pausa no topo"],
    variations: ["Panturrilha sentado", "Panturrilha no leg press"],
  },
  {
    slug: "goblet-squat",
    name: "Agachamento goblet",
    primaryMuscle: "legs",
    muscles: ["legs", "glutes", "core"],
    equipment: "dumbbell",
    instructions: "Segure um halter junto ao peito e agache mantendo o tronco ereto, depois suba.",
    tips: ["Cotovelos por dentro dos joelhos", "Peso nos calcanhares"],
    variations: ["Agachamento sumô"],
  },
  {
    slug: "bulgarian-split-squat",
    name: "Agachamento búlgaro",
    primaryMuscle: "legs",
    muscles: ["legs", "glutes"],
    equipment: "dumbbell",
    instructions: "Com um pé apoiado atrás no banco, desça flexionando a perna da frente e suba.",
    tips: ["Tronco levemente à frente", "Joelho estável"],
    variations: ["Búlgaro com barra"],
  },
  {
    slug: "glute-bridge",
    name: "Ponte de glúteo",
    primaryMuscle: "glutes",
    muscles: ["glutes", "legs"],
    equipment: "bodyweight",
    instructions: "Deitado, eleve o quadril contraindo os glúteos e desça controlando.",
    tips: ["Aperte os glúteos no topo", "Não hiperestenda a lombar"],
    variations: ["Ponte unilateral"],
  },
  {
    slug: "cable-kickback",
    name: "Glúteo no cabo",
    primaryMuscle: "glutes",
    muscles: ["glutes"],
    equipment: "cable",
    instructions:
      "Com a caneleira na polia baixa, estenda a perna para trás contraindo o glúteo e retorne.",
    tips: ["Não arqueie a lombar", "Movimento controlado"],
    variations: ["Glúteo quatro apoios"],
  },
  {
    slug: "arnold-press",
    name: "Desenvolvimento Arnold",
    primaryMuscle: "shoulders",
    muscles: ["shoulders", "triceps"],
    equipment: "dumbbell",
    instructions: "Comece com as palmas para você e gire os halteres ao empurrar acima da cabeça.",
    tips: ["Movimento fluido", "Não hiperestenda a lombar"],
    variations: ["Desenvolvimento neutro"],
  },
  {
    slug: "face-pull",
    name: "Face pull",
    primaryMuscle: "shoulders",
    muscles: ["shoulders", "back"],
    equipment: "cable",
    instructions:
      "Na polia alta com corda, puxe em direção ao rosto abrindo os cotovelos e retorne.",
    tips: ["Cotovelos altos", "Contraia a parte posterior do ombro"],
    variations: ["Face pull deitado"],
  },
  {
    slug: "front-raise",
    name: "Elevação frontal",
    primaryMuscle: "shoulders",
    muscles: ["shoulders"],
    equipment: "dumbbell",
    instructions: "Eleve os halteres à frente até a altura dos ombros e desça controlando.",
    tips: ["Não balance o tronco", "Cotovelos levemente flexionados"],
    variations: ["Elevação frontal com anilha"],
  },
  {
    slug: "hammer-curl",
    name: "Rosca martelo",
    primaryMuscle: "biceps",
    muscles: ["biceps"],
    equipment: "dumbbell",
    instructions:
      "Com pegada neutra (palmas frente a frente), flexione os cotovelos e desça controlando.",
    tips: ["Cotovelos fixos", "Sem impulso"],
    variations: ["Rosca martelo na corda"],
  },
  {
    slug: "preacher-curl",
    name: "Rosca Scott",
    primaryMuscle: "biceps",
    muscles: ["biceps"],
    equipment: "machine",
    instructions:
      "Apoie os braços no banco Scott e flexione os cotovelos elevando a barra, depois desça.",
    tips: ["Não estenda totalmente no final", "Controle a descida"],
    variations: ["Rosca Scott unilateral"],
  },
  {
    slug: "concentration-curl",
    name: "Rosca concentrada",
    primaryMuscle: "biceps",
    muscles: ["biceps"],
    equipment: "dumbbell",
    instructions: "Sentado, apoie o cotovelo na coxa e flexione o braço concentrando no bíceps.",
    tips: ["Isole o bíceps", "Sem balanço"],
    variations: [],
  },
  {
    slug: "overhead-triceps-extension",
    name: "Tríceps testa",
    primaryMuscle: "triceps",
    muscles: ["triceps"],
    equipment: "barbell",
    instructions: "Deitado, flexione os cotovelos descendo a barra até a testa e estenda de volta.",
    tips: ["Cotovelos imóveis", "Controle a descida"],
    variations: ["Tríceps testa com halteres"],
  },
  {
    slug: "triceps-dips",
    name: "Mergulho no banco",
    primaryMuscle: "triceps",
    muscles: ["triceps", "chest", "shoulders"],
    equipment: "bodyweight",
    instructions:
      "Apoie as mãos no banco atrás de você e desça flexionando os cotovelos, depois empurre de volta.",
    tips: ["Cotovelos apontados para trás", "Não desça demais"],
    variations: ["Mergulho nas paralelas"],
  },
  {
    slug: "triceps-kickback",
    name: "Tríceps coice",
    primaryMuscle: "triceps",
    muscles: ["triceps"],
    equipment: "dumbbell",
    instructions:
      "Com o tronco inclinado, estenda o cotovelo para trás contraindo o tríceps e retorne.",
    tips: ["Braço paralelo ao chão", "Cotovelo fixo"],
    variations: ["Coice na polia"],
  },
  {
    slug: "hanging-leg-raise",
    name: "Elevação de pernas na barra",
    primaryMuscle: "core",
    muscles: ["core"],
    equipment: "bodyweight",
    instructions:
      "Pendurado na barra, eleve as pernas estendidas ou joelhos até a altura do quadril.",
    tips: ["Evite balançar", "Controle a descida"],
    variations: ["Joelhos ao peito"],
  },
  {
    slug: "russian-twist",
    name: "Russian twist",
    primaryMuscle: "core",
    muscles: ["core"],
    equipment: "bodyweight",
    instructions: "Sentado com tronco inclinado, gire o tronco de um lado ao outro tocando o chão.",
    tips: ["Mantenha o abdômen contraído", "Movimento controlado"],
    variations: ["Russian twist com peso"],
  },
  {
    slug: "mountain-climber",
    name: "Escalador",
    primaryMuscle: "core",
    muscles: ["core", "legs", "shoulders"],
    equipment: "bodyweight",
    instructions: "Em prancha alta, leve os joelhos ao peito alternadamente em ritmo acelerado.",
    tips: ["Quadril estável", "Ritmo constante"],
    variations: ["Escalador cruzado"],
  },
  {
    slug: "burpee",
    name: "Burpee",
    primaryMuscle: "fullBody",
    muscles: ["fullBody", "legs", "chest", "core"],
    equipment: "bodyweight",
    instructions:
      "Agache, apoie as mãos, jogue os pés para trás, faça uma flexão, retorne e salte.",
    tips: ["Mantenha o ritmo", "Controle a aterrissagem"],
    variations: ["Burpee sem flexão"],
  },
  {
    slug: "kettlebell-swing",
    name: "Swing com kettlebell",
    primaryMuscle: "fullBody",
    muscles: ["fullBody", "glutes", "back", "legs"],
    equipment: "other",
    instructions:
      "Com o kettlebell entre as pernas, projete o quadril à frente impulsionando o peso até a altura do ombro.",
    tips: ["Força vem do quadril", "Coluna neutra"],
    variations: ["Swing americano"],
  },
  {
    slug: "rowing-machine",
    name: "Remo ergômetro",
    primaryMuscle: "fullBody",
    muscles: ["fullBody", "back", "legs"],
    equipment: "machine",
    instructions:
      "Empurre com as pernas, incline o tronco e puxe a alça ao abdômen; retorne na ordem inversa.",
    tips: ["Pernas primeiro", "Ritmo constante"],
    variations: [],
  },
];
